// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProductAttribute("GroupShareKit")]
[assembly: AssemblyVersionAttribute("0.6.0")]
[assembly: AssemblyFileVersionAttribute("0.6.0")]
[assembly: ComVisibleAttribute(false)]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyProduct = "GroupShareKit";
        internal const System.String AssemblyVersion = "0.6.0";
        internal const System.String AssemblyFileVersion = "0.6.0";
        internal const System.Boolean ComVisible = false;
    }
}
