// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProductAttribute("GroupShareKit")]
[assembly: AssemblyVersionAttribute("1.1")]
[assembly: AssemblyFileVersionAttribute("1.1")]
[assembly: ComVisibleAttribute(false)]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyProduct = "GroupShareKit";
        internal const System.String AssemblyVersion = "1.1";
        internal const System.String AssemblyFileVersion = "1.1";
        internal const System.Boolean ComVisible = false;
    }
}
